title: Frederick Liu
description: Frederick's Liu Personal Website; Software Engineer at Snap Inc.; Graduated from CMU, LTI (MLT)
email: frederick0329@gmail.com
github_username: frederick0329
linkedin_username: frederick-liu
twitter_username:
plugins:
  - jekyll-seo-tag