title: Frederick Liu
email: frederick0329@gmail.com
github_username: frederick0329
linkedin_username: frederick-liu
twitter_username: frederick0329
google_scholar: iJbdUkQAAAAJ&hl
plugins:
  - jekyll-seo-tag
