title: Frederick Liu
description: Frederick's Liu
email: frederick0329@gmail.com
github_username: frederick0329
linkedin_username: frederick-liu
twitter_username: frederick0329
plugins:
  - jekyll-seo-tag
